dependencies:
  - python=3.8
  - pip:
    - dask[complete]
    - dask_geopandas
    - dask_mpi
    - mpi4py
    - pyarrow
    - adlfs
    - planetary-computer
    - pystac-client
    - azureml-mlflow
name: dask-mpi
